#!/bin/ksh

. /etc/pragnastic/pragnastic.conf
. /etc/pragnastic/pragnastic.subr

_LAST_MSG_FILE=/tmp/pragnastic-status.last.msg

notify_without_dupes() { # params: msg
    msg=$1
    [ -e $_LAST_MSG_FILE ] && last_msg="`cat $_LAST_MSG_FILE`"
    _cmp_msg=`echo $msg | tr "\n" " "`
    if [ "`echo $_cmp_msg | sha256`" != "`echo $last_msg | sha256`" ]; then
        notify "$msg"
        print -- "$msg" >$_LAST_MSG_FILE
    else
        log "$msg"
    fi
}

softraid_mount=`mount | grep /vol/data`
[ $? == 0 ] || { notify_without_dupes "[WARNING] data softraid status check failed: unable to determine softraid status, device is not mounted" >&2; exit 1; }

softraid_device=`echo $softraid_mount | cut -b6-8`
[ -n "$softraid_device" ] || { notify_without_dupes "[WARNING] data softraid status check failed: unable to determine device" >&2; exit 2; }

softraid_status=`sysctl hw.sensors.softraid0 | grep $softraid_device`
[ $? == 0 ] || { notify_without_dupes "[WARNING] data softraid status check failed: no sensor data available for device $softraid_device" >&2; exit 3; }

softraid_short_status=`echo $softraid_status | cut -b29-`
[ "$softraid_short_status" != "online ($softraid_device), OK" ] && { notify_without_dupes "[WARNING] data softraid status: $softraid_short_status\n`bioctl $softraid_device`" >&2; exit 3; }

rm $_LAST_MSG_FILE
log "data softraid status: $softraid_short_status"
